# Install script for directory: /home/nfherrin/research/MPACT/Futility/unit_tests

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/home/nfherrin/research/MPACT/Futility/Futilitybuild/install")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "DEBUG")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testDBC/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testUnitTest/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testSelectedKinds/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testWaterSatProperties/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testArrayUtils/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testElementsIsotopes/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testExtendedMath/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testBLAS/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testStrings/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testTimes/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testGeom_Points/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testGeom_Line/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testGeom_Plane/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testGeom_CircCyl/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testGeom_Box/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testGeom_Graph/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testGeom_Poly/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testGeom/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testSorting/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testMeshTransfer/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testSearch/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testBinaryTrees/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testExceptionHandler/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testSpaceFillingCurve/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testAllocs/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testParameterLists/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testFileType_XML/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testIOutil/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testFileType_Base/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testFileType_Fortran/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testFileType_Input/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testFileType_Log/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testFileType_DA32/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testFileType_Checkpoint/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testParallelEnv/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testExpTables/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testVTKFiles/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testVTUFiles/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testCmdLineProc/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testVectorTypes/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testMatrixTypes/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testPreconditionerTypes/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testLinearSolver/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testLinearSolver_Multigrid/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testMultigridMesh/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testEigenvalueSolver/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testODESolver/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testAndersonAcceleration/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testStochasticSampler/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testPartitionGraph/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testFutilityComputingEnvironment/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testRSORprecon/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/ILUvsRSOR/cmake_install.cmake")
  include("/home/nfherrin/research/MPACT/Futility/Futilitybuild/unit_tests/testAllocsOOM/cmake_install.cmake")

endif()

