    !> @copybrief ParameterLists::initChar
    !> @copydetails ParameterLists::initChar
    PROCEDURE,PASS,NON_OVERRIDABLE :: initCHAR
    !> @copybrief Parameterlists::initSBK0
    !> @copydetails Parameterlists::initSBK0
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSBK0
    !> @copybrief Parameterlists::initSBK1
    !> @copydetails Parameterlists::initSBK1
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSBK1
    !> @copybrief Parameterlists::initSBK2
    !> @copydetails Parameterlists::initSBK2
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSBK2
    !> @copybrief Parameterlists::initSBK3
    !> @copydetails Parameterlists::initSBK3
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSBK3
    !> @copybrief Parameterlists::initSBK4
    !> @copydetails Parameterlists::initSBK4
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSBK4
    !> @copybrief Parameterlists::initSBK5
    !> @copydetails Parameterlists::initSBK5
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSBK5
    !> @copybrief Parameterlists::initSBK6
    !> @copydetails Parameterlists::initSBK6
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSBK6
    !> @copybrief Parameterlists::initSBK7
    !> @copydetails Parameterlists::initSBK7
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSBK7
    !> @copybrief Parameterlists::initSNK0
    !> @copydetails Parameterlists::initSNK0
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSNK0
    !> @copybrief Parameterlists::initSNK1
    !> @copydetails Parameterlists::initSNK1
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSNK1
    !> @copybrief Parameterlists::initSNK2
    !> @copydetails Parameterlists::initSNK2
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSNK2
    !> @copybrief Parameterlists::initSNK3
    !> @copydetails Parameterlists::initSNK3
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSNK3
    !> @copybrief Parameterlists::initSNK4
    !> @copydetails Parameterlists::initSNK4
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSNK4
    !> @copybrief Parameterlists::initSNK5
    !> @copydetails Parameterlists::initSNK5
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSNK5
    !> @copybrief Parameterlists::initSNK6
    !> @copydetails Parameterlists::initSNK6
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSNK6
    !> @copybrief Parameterlists::initSNK7
    !> @copydetails Parameterlists::initSNK7
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSNK7
    !> @copybrief Parameterlists::initSLK0
    !> @copydetails Parameterlists::initSLK0
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSLK0
    !> @copybrief Parameterlists::initSLK1
    !> @copydetails Parameterlists::initSLK1
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSLK1
    !> @copybrief Parameterlists::initSLK2
    !> @copydetails Parameterlists::initSLK2
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSLK2
    !> @copybrief Parameterlists::initSLK3
    !> @copydetails Parameterlists::initSLK3
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSLK3
    !> @copybrief Parameterlists::initSLK4
    !> @copydetails Parameterlists::initSLK4
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSLK4
    !> @copybrief Parameterlists::initSLK5
    !> @copydetails Parameterlists::initSLK5
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSLK5
    !> @copybrief Parameterlists::initSLK6
    !> @copydetails Parameterlists::initSLK6
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSLK6
    !> @copybrief Parameterlists::initSLK7
    !> @copydetails Parameterlists::initSLK7
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSLK7
    !> @copybrief Parameterlists::initSSK0
    !> @copydetails Parameterlists::initSSK0
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSSK0
    !> @copybrief Parameterlists::initSSK1
    !> @copydetails Parameterlists::initSSK1
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSSK1
    !> @copybrief Parameterlists::initSSK2
    !> @copydetails Parameterlists::initSSK2
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSSK2
    !> @copybrief Parameterlists::initSSK3
    !> @copydetails Parameterlists::initSSK3
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSSK3
    !> @copybrief Parameterlists::initSSK4
    !> @copydetails Parameterlists::initSSK4
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSSK4
    !> @copybrief Parameterlists::initSSK5
    !> @copydetails Parameterlists::initSSK5
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSSK5
    !> @copybrief Parameterlists::initSSK6
    !> @copydetails Parameterlists::initSSK6
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSSK6
    !> @copybrief Parameterlists::initSSK7
    !> @copydetails Parameterlists::initSSK7
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSSK7
    !> @copybrief Parameterlists::initSDK0
    !> @copydetails Parameterlists::initSDK0
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSDK0
    !> @copybrief Parameterlists::initSDK1
    !> @copydetails Parameterlists::initSDK1
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSDK1
    !> @copybrief Parameterlists::initSDK2
    !> @copydetails Parameterlists::initSDK2
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSDK2
    !> @copybrief Parameterlists::initSDK3
    !> @copydetails Parameterlists::initSDK3
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSDK3
    !> @copybrief Parameterlists::initSDK4
    !> @copydetails Parameterlists::initSDK4
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSDK4
    !> @copybrief Parameterlists::initSDK5
    !> @copydetails Parameterlists::initSDK5
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSDK5
    !> @copybrief Parameterlists::initSDK6
    !> @copydetails Parameterlists::initSDK6
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSDK6
    !> @copybrief Parameterlists::initSDK7
    !> @copydetails Parameterlists::initSDK7
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSDK7
    !> @copybrief Parameterlists::initSTR0
    !> @copydetails Parameterlists::initSTR0
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSTR0
    !> @copybrief Parameterlists::initSTR1
    !> @copydetails Parameterlists::initSTR1
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSTR1
    !> @copybrief Parameterlists::initSTR2
    !> @copydetails Parameterlists::initSTR2
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSTR2
    !> @copybrief Parameterlists::initSTR3
    !> @copydetails Parameterlists::initSTR3
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSTR3
    !> @copybrief Parameterlists::initSTR4
    !> @copydetails Parameterlists::initSTR4
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSTR4
    !> @copybrief Parameterlists::initSTR5
    !> @copydetails Parameterlists::initSTR5
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSTR5
    !> @copybrief Parameterlists::initSTR6
    !> @copydetails Parameterlists::initSTR6
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSTR6
    !> @copybrief Parameterlists::initSTR7
    !> @copydetails Parameterlists::initSTR7
    PROCEDURE,PASS,NON_OVERRIDABLE :: initSTR7