!
!-------------------------------------------------------------------------------
!> @brief Adds a @c ParamNode to a @c ParamType
!> @param this the @c ParamType to add to
!> @param name the name of the node to add
!> @param val the node to add to @c this
!>
SUBROUTINE addNode(this,name,val)
  CLASS(ParamType),INTENT(INOUT) :: this
  CHARACTER(LEN=*),INTENT(IN) :: name
  CLASS(ParamNode),INTENT(IN) :: val

  IF(ALLOCATED(val%val)) THEN
    SELECTTYPE(ptr => val%val)
    TYPE IS(Param_SBK0)
      CALL this%addSBK0(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SBK1)
      CALL this%addSBK1(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SBK2)
      CALL this%addSBK2(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SBK3)
      CALL this%addSBK3(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SBK4)
      CALL this%addSBK4(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SBK5)
      CALL this%addSBK5(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SBK6)
      CALL this%addSBK6(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SBK7)
      CALL this%addSBK7(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SNK0)
      CALL this%addSNK0(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SNK1)
      CALL this%addSNK1(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SNK2)
      CALL this%addSNK2(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SNK3)
      CALL this%addSNK3(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SNK4)
      CALL this%addSNK4(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SNK5)
      CALL this%addSNK5(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SNK6)
      CALL this%addSNK6(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SNK7)
      CALL this%addSNK7(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SLK0)
      CALL this%addSLK0(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SLK1)
      CALL this%addSLK1(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SLK2)
      CALL this%addSLK2(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SLK3)
      CALL this%addSLK3(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SLK4)
      CALL this%addSLK4(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SLK5)
      CALL this%addSLK5(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SLK6)
      CALL this%addSLK6(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SLK7)
      CALL this%addSLK7(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SSK0)
      CALL this%addSSK0(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SSK1)
      CALL this%addSSK1(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SSK2)
      CALL this%addSSK2(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SSK3)
      CALL this%addSSK3(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SSK4)
      CALL this%addSSK4(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SSK5)
      CALL this%addSSK5(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SSK6)
      CALL this%addSSK6(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SSK7)
      CALL this%addSSK7(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SDK0)
      CALL this%addSDK0(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SDK1)
      CALL this%addSDK1(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SDK2)
      CALL this%addSDK2(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SDK3)
      CALL this%addSDK3(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SDK4)
      CALL this%addSDK4(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SDK5)
      CALL this%addSDK5(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SDK6)
      CALL this%addSDK6(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_SDK7)
      CALL this%addSDK7(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_STR0)
      CALL this%addSTR0(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_STR1)
      CALL this%addSTR1(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_STR2)
      CALL this%addSTR2(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_STR3)
      CALL this%addSTR3(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_STR4)
      CALL this%addSTR4(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_STR5)
      CALL this%addSTR5(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_STR6)
      CALL this%addSTR6(name,ptr%p,CHAR(val%description))
    TYPE IS(Param_STR7)
      CALL this%addSTR7(name,ptr%p,CHAR(val%description))
    ENDSELECT
  ENDIF

ENDSUBROUTINE addNode
