    !List of get methods
    !> @copybrief ParameterLists::getTree
    !> @copybrief ParameterLists::getTree
    PROCEDURE,PASS,PRIVATE :: getTree
    !> @copybrief ParameterLists::getIterator
    !> @copybrief ParameterLists::getIterator
    PROCEDURE,PASS,PRIVATE :: getIterator
    !> @copybrief ParameterLists::getCHAR
    !> @copybrief ParameterLists::getCHAR
    PROCEDURE,PASS,PRIVATE :: getCHAR
    !> @copybrief ParameterLists::getStrCHAR
    !> @copybrief ParameterLists::getStrCHAR
    PROCEDURE,PASS,PRIVATE :: getStrCHAR
    !> @copybrief ParameterLists::getSBK0
    !> @copydetails ParameterLists::getSBK0
    PROCEDURE,PASS,PRIVATE :: getSBK0
    !> @copybrief ParameterLists::getSBK1
    !> @copydetails ParameterLists::getSBK1
    PROCEDURE,PASS,PRIVATE :: getSBK1
    !> @copybrief ParameterLists::getSBK2
    !> @copydetails ParameterLists::getSBK2
    PROCEDURE,PASS,PRIVATE :: getSBK2
    !> @copybrief ParameterLists::getSBK3
    !> @copydetails ParameterLists::getSBK3
    PROCEDURE,PASS,PRIVATE :: getSBK3
    !> @copybrief ParameterLists::getSBK4
    !> @copydetails ParameterLists::getSBK4
    PROCEDURE,PASS,PRIVATE :: getSBK4
    !> @copybrief ParameterLists::getSBK5
    !> @copydetails ParameterLists::getSBK5
    PROCEDURE,PASS,PRIVATE :: getSBK5
    !> @copybrief ParameterLists::getSBK6
    !> @copydetails ParameterLists::getSBK6
    PROCEDURE,PASS,PRIVATE :: getSBK6
    !> @copybrief ParameterLists::getSBK7
    !> @copydetails ParameterLists::getSBK7
    PROCEDURE,PASS,PRIVATE :: getSBK7
    !> @copybrief ParameterLists::getSNK0
    !> @copydetails ParameterLists::getSNK0
    PROCEDURE,PASS,PRIVATE :: getSNK0
    !> @copybrief ParameterLists::getSNK1
    !> @copydetails ParameterLists::getSNK1
    PROCEDURE,PASS,PRIVATE :: getSNK1
    !> @copybrief ParameterLists::getSNK2
    !> @copydetails ParameterLists::getSNK2
    PROCEDURE,PASS,PRIVATE :: getSNK2
    !> @copybrief ParameterLists::getSNK3
    !> @copydetails ParameterLists::getSNK3
    PROCEDURE,PASS,PRIVATE :: getSNK3
    !> @copybrief ParameterLists::getSNK4
    !> @copydetails ParameterLists::getSNK4
    PROCEDURE,PASS,PRIVATE :: getSNK4
    !> @copybrief ParameterLists::getSNK5
    !> @copydetails ParameterLists::getSNK5
    PROCEDURE,PASS,PRIVATE :: getSNK5
    !> @copybrief ParameterLists::getSNK6
    !> @copydetails ParameterLists::getSNK6
    PROCEDURE,PASS,PRIVATE :: getSNK6
    !> @copybrief ParameterLists::getSNK7
    !> @copydetails ParameterLists::getSNK7
    PROCEDURE,PASS,PRIVATE :: getSNK7
    !> @copybrief ParameterLists::getSLK0
    !> @copydetails ParameterLists::getSLK0
    PROCEDURE,PASS,PRIVATE :: getSLK0
    !> @copybrief ParameterLists::getSLK1
    !> @copydetails ParameterLists::getSLK1
    PROCEDURE,PASS,PRIVATE :: getSLK1
    !> @copybrief ParameterLists::getSLK2
    !> @copydetails ParameterLists::getSLK2
    PROCEDURE,PASS,PRIVATE :: getSLK2
    !> @copybrief ParameterLists::getSLK3
    !> @copydetails ParameterLists::getSLK3
    PROCEDURE,PASS,PRIVATE :: getSLK3
    !> @copybrief ParameterLists::getSLK4
    !> @copydetails ParameterLists::getSLK4
    PROCEDURE,PASS,PRIVATE :: getSLK4
    !> @copybrief ParameterLists::getSLK5
    !> @copydetails ParameterLists::getSLK5
    PROCEDURE,PASS,PRIVATE :: getSLK5
    !> @copybrief ParameterLists::getSLK6
    !> @copydetails ParameterLists::getSLK6
    PROCEDURE,PASS,PRIVATE :: getSLK6
    !> @copybrief ParameterLists::getSLK7
    !> @copydetails ParameterLists::getSLK7
    PROCEDURE,PASS,PRIVATE :: getSLK7
    !> @copybrief ParameterLists::getSSK0
    !> @copydetails ParameterLists::getSSK0
    PROCEDURE,PASS,PRIVATE :: getSSK0
    !> @copybrief ParameterLists::getSSK1
    !> @copydetails ParameterLists::getSSK1
    PROCEDURE,PASS,PRIVATE :: getSSK1
    !> @copybrief ParameterLists::getSSK2
    !> @copydetails ParameterLists::getSSK2
    PROCEDURE,PASS,PRIVATE :: getSSK2
    !> @copybrief ParameterLists::getSSK3
    !> @copydetails ParameterLists::getSSK3
    PROCEDURE,PASS,PRIVATE :: getSSK3
    !> @copybrief ParameterLists::getSSK4
    !> @copydetails ParameterLists::getSSK4
    PROCEDURE,PASS,PRIVATE :: getSSK4
    !> @copybrief ParameterLists::getSSK5
    !> @copydetails ParameterLists::getSSK5
    PROCEDURE,PASS,PRIVATE :: getSSK5
    !> @copybrief ParameterLists::getSSK6
    !> @copydetails ParameterLists::getSSK6
    PROCEDURE,PASS,PRIVATE :: getSSK6
    !> @copybrief ParameterLists::getSSK7
    !> @copydetails ParameterLists::getSSK7
    PROCEDURE,PASS,PRIVATE :: getSSK7
    !> @copybrief ParameterLists::getSDK0
    !> @copydetails ParameterLists::getSDK0
    PROCEDURE,PASS,PRIVATE :: getSDK0
    !> @copybrief ParameterLists::getSDK1
    !> @copydetails ParameterLists::getSDK1
    PROCEDURE,PASS,PRIVATE :: getSDK1
    !> @copybrief ParameterLists::getSDK2
    !> @copydetails ParameterLists::getSDK2
    PROCEDURE,PASS,PRIVATE :: getSDK2
    !> @copybrief ParameterLists::getSDK3
    !> @copydetails ParameterLists::getSDK3
    PROCEDURE,PASS,PRIVATE :: getSDK3
    !> @copybrief ParameterLists::getSDK4
    !> @copydetails ParameterLists::getSDK4
    PROCEDURE,PASS,PRIVATE :: getSDK4
    !> @copybrief ParameterLists::getSDK5
    !> @copydetails ParameterLists::getSDK5
    PROCEDURE,PASS,PRIVATE :: getSDK5
    !> @copybrief ParameterLists::getSDK6
    !> @copydetails ParameterLists::getSDK6
    PROCEDURE,PASS,PRIVATE :: getSDK6
    !> @copybrief ParameterLists::getSDK7
    !> @copydetails ParameterLists::getSDK7
    PROCEDURE,PASS,PRIVATE :: getSDK7
    !> @copybrief ParameterLists::getSTR0
    !> @copydetails ParameterLists::getSTR0
    PROCEDURE,PASS,PRIVATE :: getSTR0
    !> @copybrief ParameterLists::getSTR1
    !> @copydetails ParameterLists::getSTR1
    PROCEDURE,PASS,PRIVATE :: getSTR1
    !> @copybrief ParameterLists::getSTR2
    !> @copydetails ParameterLists::getSTR2
    PROCEDURE,PASS,PRIVATE :: getSTR2
    !> @copybrief ParameterLists::getSTR3
    !> @copydetails ParameterLists::getSTR3
    PROCEDURE,PASS,PRIVATE :: getSTR3
    !> @copybrief ParameterLists::getSTR4
    !> @copydetails ParameterLists::getSTR4
    PROCEDURE,PASS,PRIVATE :: getSTR4
    !> @copybrief ParameterLists::getSTR5
    !> @copydetails ParameterLists::getSTR5
    PROCEDURE,PASS,PRIVATE :: getSTR5
    !> @copybrief ParameterLists::getSTR6
    !> @copydetails ParameterLists::getSTR6
    PROCEDURE,PASS,PRIVATE :: getSTR6
    !> @copybrief ParameterLists::getSTR7
    !> @copydetails ParameterLists::getSTR7
    PROCEDURE,PASS,PRIVATE :: getSTR7
    GENERIC :: get => getTree,getIterator,getCHAR,getStrCHAR, &
        getSBK0,getSBK1,getSBK2,getSBK3,getSBK4,getSBK5,getSBK6,getSBK7, &
        getSNK0,getSNK1,getSNK2,getSNK3,getSNK4,getSNK5,getSNK6,getSNK7, &
        getSLK0,getSLK1,getSLK2,getSLK3,getSLK4,getSLK5,getSLK6,getSLK7, &
        getSSK0,getSSK1,getSSK2,getSSK3,getSSK4,getSSK5,getSSK6,getSSK7, &
        getSDK0,getSDK1,getSDK2,getSDK3,getSDK4,getSDK5,getSDK6,getSDK7, &
        getSTR0,getSTR1,getSTR2,getSTR3,getSTR4,getSTR5,getSTR6,getSTR7
    !List of add methods
    !> @copybrief ParameterLists::addTree
    !> @copydetails ParameterLists::addTree
    PROCEDURE,PASS,PRIVATE :: addTree
    !> @copybrief ParameterLists::addNode
    !> @copydetails ParameterLists::addNode
    PROCEDURE,PASS,PRIVATE :: addNode
    !> @copybrief ParameterLists::addCHAR
    !> @copydetails ParameterLists::addCHAR
    PROCEDURE,PASS,PRIVATE :: addCHAR
    !> @copybrief ParameterLists::addSBK0
    !> @copydetails ParameterLists::addSBK0
    PROCEDURE,PASS,PRIVATE :: addSBK0
    !> @copybrief ParameterLists::addSBK1
    !> @copydetails ParameterLists::addSBK1
    PROCEDURE,PASS,PRIVATE :: addSBK1
    !> @copybrief ParameterLists::addSBK2
    !> @copydetails ParameterLists::addSBK2
    PROCEDURE,PASS,PRIVATE :: addSBK2
    !> @copybrief ParameterLists::addSBK3
    !> @copydetails ParameterLists::addSBK3
    PROCEDURE,PASS,PRIVATE :: addSBK3
    !> @copybrief ParameterLists::addSBK4
    !> @copydetails ParameterLists::addSBK4
    PROCEDURE,PASS,PRIVATE :: addSBK4
    !> @copybrief ParameterLists::addSBK5
    !> @copydetails ParameterLists::addSBK5
    PROCEDURE,PASS,PRIVATE :: addSBK5
    !> @copybrief ParameterLists::addSBK6
    !> @copydetails ParameterLists::addSBK6
    PROCEDURE,PASS,PRIVATE :: addSBK6
    !> @copybrief ParameterLists::addSBK7
    !> @copydetails ParameterLists::addSBK7
    PROCEDURE,PASS,PRIVATE :: addSBK7
    !> @copybrief ParameterLists::addSNK0
    !> @copydetails ParameterLists::addSNK0
    PROCEDURE,PASS,PRIVATE :: addSNK0
    !> @copybrief ParameterLists::addSNK1
    !> @copydetails ParameterLists::addSNK1
    PROCEDURE,PASS,PRIVATE :: addSNK1
    !> @copybrief ParameterLists::addSNK2
    !> @copydetails ParameterLists::addSNK2
    PROCEDURE,PASS,PRIVATE :: addSNK2
    !> @copybrief ParameterLists::addSNK3
    !> @copydetails ParameterLists::addSNK3
    PROCEDURE,PASS,PRIVATE :: addSNK3
    !> @copybrief ParameterLists::addSNK4
    !> @copydetails ParameterLists::addSNK4
    PROCEDURE,PASS,PRIVATE :: addSNK4
    !> @copybrief ParameterLists::addSNK5
    !> @copydetails ParameterLists::addSNK5
    PROCEDURE,PASS,PRIVATE :: addSNK5
    !> @copybrief ParameterLists::addSNK6
    !> @copydetails ParameterLists::addSNK6
    PROCEDURE,PASS,PRIVATE :: addSNK6
    !> @copybrief ParameterLists::addSNK7
    !> @copydetails ParameterLists::addSNK7
    PROCEDURE,PASS,PRIVATE :: addSNK7
    !> @copybrief ParameterLists::addSLK0
    !> @copydetails ParameterLists::addSLK0
    PROCEDURE,PASS,PRIVATE :: addSLK0
    !> @copybrief ParameterLists::addSLK1
    !> @copydetails ParameterLists::addSLK1
    PROCEDURE,PASS,PRIVATE :: addSLK1
    !> @copybrief ParameterLists::addSLK2
    !> @copydetails ParameterLists::addSLK2
    PROCEDURE,PASS,PRIVATE :: addSLK2
    !> @copybrief ParameterLists::addSLK3
    !> @copydetails ParameterLists::addSLK3
    PROCEDURE,PASS,PRIVATE :: addSLK3
    !> @copybrief ParameterLists::addSLK4
    !> @copydetails ParameterLists::addSLK4
    PROCEDURE,PASS,PRIVATE :: addSLK4
    !> @copybrief ParameterLists::addSLK5
    !> @copydetails ParameterLists::addSLK5
    PROCEDURE,PASS,PRIVATE :: addSLK5
    !> @copybrief ParameterLists::addSLK6
    !> @copydetails ParameterLists::addSLK6
    PROCEDURE,PASS,PRIVATE :: addSLK6
    !> @copybrief ParameterLists::addSLK7
    !> @copydetails ParameterLists::addSLK7
    PROCEDURE,PASS,PRIVATE :: addSLK7
    !> @copybrief ParameterLists::addSSK0
    !> @copydetails ParameterLists::addSSK0
    PROCEDURE,PASS,PRIVATE :: addSSK0
    !> @copybrief ParameterLists::addSSK1
    !> @copydetails ParameterLists::addSSK1
    PROCEDURE,PASS,PRIVATE :: addSSK1
    !> @copybrief ParameterLists::addSSK2
    !> @copydetails ParameterLists::addSSK2
    PROCEDURE,PASS,PRIVATE :: addSSK2
    !> @copybrief ParameterLists::addSSK3
    !> @copydetails ParameterLists::addSSK3
    PROCEDURE,PASS,PRIVATE :: addSSK3
    !> @copybrief ParameterLists::addSSK4
    !> @copydetails ParameterLists::addSSK4
    PROCEDURE,PASS,PRIVATE :: addSSK4
    !> @copybrief ParameterLists::addSSK5
    !> @copydetails ParameterLists::addSSK5
    PROCEDURE,PASS,PRIVATE :: addSSK5
    !> @copybrief ParameterLists::addSSK6
    !> @copydetails ParameterLists::addSSK6
    PROCEDURE,PASS,PRIVATE :: addSSK6
    !> @copybrief ParameterLists::addSSK7
    !> @copydetails ParameterLists::addSSK7
    PROCEDURE,PASS,PRIVATE :: addSSK7
    !> @copybrief ParameterLists::addSDK0
    !> @copydetails ParameterLists::addSDK0
    PROCEDURE,PASS,PRIVATE :: addSDK0
    !> @copybrief ParameterLists::addSDK1
    !> @copydetails ParameterLists::addSDK1
    PROCEDURE,PASS,PRIVATE :: addSDK1
    !> @copybrief ParameterLists::addSDK2
    !> @copydetails ParameterLists::addSDK2
    PROCEDURE,PASS,PRIVATE :: addSDK2
    !> @copybrief ParameterLists::addSDK3
    !> @copydetails ParameterLists::addSDK3
    PROCEDURE,PASS,PRIVATE :: addSDK3
    !> @copybrief ParameterLists::addSDK4
    !> @copydetails ParameterLists::addSDK4
    PROCEDURE,PASS,PRIVATE :: addSDK4
    !> @copybrief ParameterLists::addSDK5
    !> @copydetails ParameterLists::addSDK5
    PROCEDURE,PASS,PRIVATE :: addSDK5
    !> @copybrief ParameterLists::addSDK6
    !> @copydetails ParameterLists::addSDK6
    PROCEDURE,PASS,PRIVATE :: addSDK6
    !> @copybrief ParameterLists::addSDK7
    !> @copydetails ParameterLists::addSDK7
    PROCEDURE,PASS,PRIVATE :: addSDK7
    !> @copybrief ParameterLists::addSTR0
    !> @copydetails ParameterLists::addSTR0
    PROCEDURE,PASS,PRIVATE :: addSTR0
    !> @copybrief ParameterLists::addSTR1
    !> @copydetails ParameterLists::addSTR1
    PROCEDURE,PASS,PRIVATE :: addSTR1
    !> @copybrief ParameterLists::addSTR2
    !> @copydetails ParameterLists::addSTR2
    PROCEDURE,PASS,PRIVATE :: addSTR2
    !> @copybrief ParameterLists::addSTR3
    !> @copydetails ParameterLists::addSTR3
    PROCEDURE,PASS,PRIVATE :: addSTR3
    !> @copybrief ParameterLists::addSTR4
    !> @copydetails ParameterLists::addSTR4
    PROCEDURE,PASS,PRIVATE :: addSTR4
    !> @copybrief ParameterLists::addSTR5
    !> @copydetails ParameterLists::addSTR5
    PROCEDURE,PASS,PRIVATE :: addSTR5
    !> @copybrief ParameterLists::addSTR6
    !> @copydetails ParameterLists::addSTR6
    PROCEDURE,PASS,PRIVATE :: addSTR6
    !> @copybrief ParameterLists::addSTR7
    !> @copydetails ParameterLists::addSTR7
    PROCEDURE,PASS,PRIVATE :: addSTR7
    GENERIC :: add => addTree,addNode,addCHAR,addSBK0,addSBK1,addSBK2,addSBK3,addSBK4,addSBK5,addSBK6,addSBK7, &
        addSNK0,addSNK1,addSNK2,addSNK3,addSNK4,addSNK5,addSNK6,addSNK7, &
        addSLK0,addSLK1,addSLK2,addSLK3,addSLK4,addSLK5,addSLK6,addSLK7, &
        addSSK0,addSSK1,addSSK2,addSSK3,addSSK4,addSSK5,addSSK6,addSSK7, &
        addSDK0,addSDK1,addSDK2,addSDK3,addSDK4,addSDK5,addSDK6,addSDK7, &
        addSTR0,addSTR1,addSTR2,addSTR3,addSTR4,addSTR5,addSTR6,addSTR7
    !List of set methods
    !> @copybrief ParameterLists::setChar
    !> @copydetails ParameterLists::setChar
    PROCEDURE,PASS,PRIVATE :: setCHAR
    !> @copybrief ParameterLists::setSBK0
    !> @copydetails ParameterLists::setSBK0
    PROCEDURE,PASS,PRIVATE :: setSBK0
    !> @copybrief ParameterLists::setSBK1
    !> @copydetails ParameterLists::setSBK1
    PROCEDURE,PASS,PRIVATE :: setSBK1
    !> @copybrief ParameterLists::setSBK2
    !> @copydetails ParameterLists::setSBK2
    PROCEDURE,PASS,PRIVATE :: setSBK2
    !> @copybrief ParameterLists::setSBK3
    !> @copydetails ParameterLists::setSBK3
    PROCEDURE,PASS,PRIVATE :: setSBK3
    !> @copybrief ParameterLists::setSBK4
    !> @copydetails ParameterLists::setSBK4
    PROCEDURE,PASS,PRIVATE :: setSBK4
    !> @copybrief ParameterLists::setSBK5
    !> @copydetails ParameterLists::setSBK5
    PROCEDURE,PASS,PRIVATE :: setSBK5
    !> @copybrief ParameterLists::setSBK6
    !> @copydetails ParameterLists::setSBK6
    PROCEDURE,PASS,PRIVATE :: setSBK6
    !> @copybrief ParameterLists::setSBK7
    !> @copydetails ParameterLists::setSBK7
    PROCEDURE,PASS,PRIVATE :: setSBK7
    !> @copybrief ParameterLists::setSNK0
    !> @copydetails ParameterLists::setSNK0
    PROCEDURE,PASS,PRIVATE :: setSNK0
    !> @copybrief ParameterLists::setSNK1
    !> @copydetails ParameterLists::setSNK1
    PROCEDURE,PASS,PRIVATE :: setSNK1
    !> @copybrief ParameterLists::setSNK2
    !> @copydetails ParameterLists::setSNK2
    PROCEDURE,PASS,PRIVATE :: setSNK2
    !> @copybrief ParameterLists::setSNK3
    !> @copydetails ParameterLists::setSNK3
    PROCEDURE,PASS,PRIVATE :: setSNK3
    !> @copybrief ParameterLists::setSNK4
    !> @copydetails ParameterLists::setSNK4
    PROCEDURE,PASS,PRIVATE :: setSNK4
    !> @copybrief ParameterLists::setSNK5
    !> @copydetails ParameterLists::setSNK5
    PROCEDURE,PASS,PRIVATE :: setSNK5
    !> @copybrief ParameterLists::setSNK6
    !> @copydetails ParameterLists::setSNK6
    PROCEDURE,PASS,PRIVATE :: setSNK6
    !> @copybrief ParameterLists::setSNK7
    !> @copydetails ParameterLists::setSNK7
    PROCEDURE,PASS,PRIVATE :: setSNK7
    !> @copybrief ParameterLists::setSLK0
    !> @copydetails ParameterLists::setSLK0
    PROCEDURE,PASS,PRIVATE :: setSLK0
    !> @copybrief ParameterLists::setSLK1
    !> @copydetails ParameterLists::setSLK1
    PROCEDURE,PASS,PRIVATE :: setSLK1
    !> @copybrief ParameterLists::setSLK2
    !> @copydetails ParameterLists::setSLK2
    PROCEDURE,PASS,PRIVATE :: setSLK2
    !> @copybrief ParameterLists::setSLK3
    !> @copydetails ParameterLists::setSLK3
    PROCEDURE,PASS,PRIVATE :: setSLK3
    !> @copybrief ParameterLists::setSLK4
    !> @copydetails ParameterLists::setSLK4
    PROCEDURE,PASS,PRIVATE :: setSLK4
    !> @copybrief ParameterLists::setSLK5
    !> @copydetails ParameterLists::setSLK5
    PROCEDURE,PASS,PRIVATE :: setSLK5
    !> @copybrief ParameterLists::setSLK6
    !> @copydetails ParameterLists::setSLK6
    PROCEDURE,PASS,PRIVATE :: setSLK6
    !> @copybrief ParameterLists::setSLK7
    !> @copydetails ParameterLists::setSLK7
    PROCEDURE,PASS,PRIVATE :: setSLK7
    !> @copybrief ParameterLists::setSSK0
    !> @copydetails ParameterLists::setSSK0
    PROCEDURE,PASS,PRIVATE :: setSSK0
    !> @copybrief ParameterLists::setSSK1
    !> @copydetails ParameterLists::setSSK1
    PROCEDURE,PASS,PRIVATE :: setSSK1
    !> @copybrief ParameterLists::setSSK2
    !> @copydetails ParameterLists::setSSK2
    PROCEDURE,PASS,PRIVATE :: setSSK2
    !> @copybrief ParameterLists::setSSK3
    !> @copydetails ParameterLists::setSSK3
    PROCEDURE,PASS,PRIVATE :: setSSK3
    !> @copybrief ParameterLists::setSSK4
    !> @copydetails ParameterLists::setSSK4
    PROCEDURE,PASS,PRIVATE :: setSSK4
    !> @copybrief ParameterLists::setSSK5
    !> @copydetails ParameterLists::setSSK5
    PROCEDURE,PASS,PRIVATE :: setSSK5
    !> @copybrief ParameterLists::setSSK6
    !> @copydetails ParameterLists::setSSK6
    PROCEDURE,PASS,PRIVATE :: setSSK6
    !> @copybrief ParameterLists::setSSK7
    !> @copydetails ParameterLists::setSSK7
    PROCEDURE,PASS,PRIVATE :: setSSK7
    !> @copybrief ParameterLists::setSDK0
    !> @copydetails ParameterLists::setSDK0
    PROCEDURE,PASS,PRIVATE :: setSDK0
    !> @copybrief ParameterLists::setSDK1
    !> @copydetails ParameterLists::setSDK1
    PROCEDURE,PASS,PRIVATE :: setSDK1
    !> @copybrief ParameterLists::setSDK2
    !> @copydetails ParameterLists::setSDK2
    PROCEDURE,PASS,PRIVATE :: setSDK2
    !> @copybrief ParameterLists::setSDK3
    !> @copydetails ParameterLists::setSDK3
    PROCEDURE,PASS,PRIVATE :: setSDK3
    !> @copybrief ParameterLists::setSDK4
    !> @copydetails ParameterLists::setSDK4
    PROCEDURE,PASS,PRIVATE :: setSDK4
    !> @copybrief ParameterLists::setSDK5
    !> @copydetails ParameterLists::setSDK5
    PROCEDURE,PASS,PRIVATE :: setSDK5
    !> @copybrief ParameterLists::setSDK6
    !> @copydetails ParameterLists::setSDK6
    PROCEDURE,PASS,PRIVATE :: setSDK6
    !> @copybrief ParameterLists::setSDK7
    !> @copydetails ParameterLists::setSDK7
    PROCEDURE,PASS,PRIVATE :: setSDK7
    !> @copybrief ParameterLists::setSTR0
    !> @copydetails ParameterLists::setSTR0
    PROCEDURE,PASS,PRIVATE :: setSTR0
    !> @copybrief ParameterLists::setSTR1
    !> @copydetails ParameterLists::setSTR1
    PROCEDURE,PASS,PRIVATE :: setSTR1
    !> @copybrief ParameterLists::setSTR2
    !> @copydetails ParameterLists::setSTR2
    PROCEDURE,PASS,PRIVATE :: setSTR2
    !> @copybrief ParameterLists::setSTR3
    !> @copydetails ParameterLists::setSTR3
    PROCEDURE,PASS,PRIVATE :: setSTR3
    !> @copybrief ParameterLists::setSTR4
    !> @copydetails ParameterLists::setSTR4
    PROCEDURE,PASS,PRIVATE :: setSTR4
    !> @copybrief ParameterLists::setSTR5
    !> @copydetails ParameterLists::setSTR5
    PROCEDURE,PASS,PRIVATE :: setSTR5
    !> @copybrief ParameterLists::setSTR6
    !> @copydetails ParameterLists::setSTR6
    PROCEDURE,PASS,PRIVATE :: setSTR6
    !> @copybrief ParameterLists::setSTR7
    !> @copydetails ParameterLists::setSTR7
    PROCEDURE,PASS,PRIVATE :: setSTR7
    GENERIC :: set => setCHAR,setSBK0,setSBK1,setSBK2,setSBK3,setSBK4,setSBK5,setSBK6,setSBK7, &
        setSNK0,setSNK1,setSNK2,setSNK3,setSNK4,setSNK5,setSNK6,setSNK7, &
        setSLK0,setSLK1,setSLK2,setSLK3,setSLK4,setSLK5,setSLK6,setSLK7, &
        setSSK0,setSSK1,setSSK2,setSSK3,setSSK4,setSSK5,setSSK6,setSSK7, &
        setSDK0,setSDK1,setSDK2,setSDK3,setSDK4,setSDK5,setSDK6,setSDK7, &
        setSTR0,setSTR1,setSTR2,setSTR3,setSTR4,setSTR5,setSTR6,setSTR7
